version: '3.9'
services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lolcina23
      POSTGRES_DB: marko-mrdja-interview  
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      my-network:
        aliases:
          - flask-app
      
  backend:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:lolcina23@db:5432/marko-mrdja-interview
    networks:
      my-network:
        aliases:
          - flask-app
    depends_on:
      - db

  frontend:
    build: ./www
    ports:
      - "3000:3000"
    networks:
      my-network:
        aliases:
          - react-app

  nginx:
    image: nginx:1.22.1-alpine
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - client-body:/var/lib/nginx/tmp 
    networks:
      - my-network 


volumes:
  db-data:
  nginx-conf:
  client-body:  
    
networks:
  my-network: